name: Create Release with Artifacts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip Views
        run: zip -r app.zip views/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: app.zip
          tag_name: ${{ env.TAG_NAME }}

        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
