name: Create Release with Artifacts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create a Tag
        id: create_tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Zip Views
        run: cd views && zip -r app.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: views/app.zip
          tag_name: ${{ env.TAG_NAME }}

        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
